#!/bin/bash
mkdir -p /tmp/db/registry
icebox --Ice.Config=./configs/icebox.config
icegridregistry --Ice.Config=configs/icegrid.config
python3 IceFlix/Main.py --Ice.Config=configs/main.config admin &
python3 IceFlix/Authenticator.py "Main:tcp -p 9090" &
python3 IceFlix/MediaCatalog.py "Main:tcp -p 9090" &
python3 IceFlix/StreamProvider.py "Main:tcp -p 9090" &
trap "kill 0" SIGINT
wait