#!/bin/bash
icebox --Ice.Config=./configs/icebox.config
python3 IceFlix/Main.py --Ice.Config=IceFlix/main_service.config admin &
python3 IceFlix/Authenticator.py "Main:tcp -p 9090" &
python3 IceFlix/MediaCatalog.py "Main:tcp -p 9090" &
python3 IceFlix/StreamProvider.py "Main:tcp -p 9090" &
trap "kill 0" SIGINT
wait